module.exports = {
  apps: [
    {
      name: "house-watch-api",
      script: "backend/server.js",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "300M",
      env: {
        NODE_ENV: "development",
        HOST: "0.0.0.0",
        PORT: 8787,
        ALLOW_ORIGIN: "*",
        STORE_PATH: "./backend/data/store.json",
        SEED_MODE: "empty",
        AUTO_REFRESH_ENABLED: "false",
        AUTO_REFRESH_HOUR: 0,
        AUTO_REFRESH_MINUTE: 30,
        BEIKE_BROWSER_ENABLED: "true",
        BEIKE_BROWSER_HEADLESS: "false",
        BEIKE_BROWSER_SESSION_DIR: "./backend/data/browser-session/beike",
        BEIKE_CHROME_PATH: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      },
      env_production: {
        NODE_ENV: "production",
        HOST: "0.0.0.0",
        PORT: 8787,
        ALLOW_ORIGIN: "https://servicewechat.com",
        STORE_PATH: "./backend/data/store.prod.json",
        SEED_MODE: "empty",
        AUTO_REFRESH_ENABLED: "true",
        AUTO_REFRESH_HOUR: 0,
        AUTO_REFRESH_MINUTE: 30,
        BEIKE_BROWSER_ENABLED: "true",
        BEIKE_BROWSER_HEADLESS: "true",
        BEIKE_BROWSER_SESSION_DIR: "./backend/data/browser-session/beike",
        BEIKE_CHROME_PATH: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      },
    },
  ],
};
